services:  
  backend:
    build:
      context: ./backend/neverlate  
    ports:      
      - "8080:8080"
    networks:      
      - neverlate-network 

  frontend:    
    build:
      context: ./frontend/neverlate
    ports:      
      - "5173:5173"
    networks:
      - neverlate-network

networks:  
  neverlate-network:
    driver: bridge
